# GENERATED BY intent
# DO NOT EDIT

default:
    @just --list

test:
    pytest -q

test-api:
    PYTHONPATH=apps/api pytest -q apps/api/tests

test-web:
    cd apps/web && npm run test

build-web:
    cd apps/web && npm run build

lint:
    ruff check .
